### ISSUE TITLE
Valerie SQL Commands

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#35]
Issue on PCI join_output transform block 4:
Error is "Some referenced variables are not in this table: Days_Elig_eff"
This looks like the same error we had, where a new variable created in the previous block can't be referenced in the following block. 
I tested this as transform block 4, but also as a completely new transform. I still get the same error

**Comment by vmeau** [comment]
it would be really useful to have a button that says "Update all" that would run since the very beginning. Maybe it's already doing it behind the scene, but as user it'd be great to know that it's happening from the very top and not from the latest query. :)

**Comment by imathews** [comment]
Totally agreed on the second comment (and fwiw, we're definitely not doing any update all behind the scenes, so be sure to click through :) 

Just broke into a separate issue, #36

**Comment by imathews** [comment]
First comment should be fixed, and will be deployed within the hour. @vmeau, could you please test when you get around to it, and if all's good, please go ahead and close this issue

**Comment by vmeau** [comment]
PCI_Elig_post block 3 ran @10:09pm
Still getting an error on the group by function:
SELECT
$Patid,
$Admit_Date,
$Pre_Admit,
$Post_Admit,
sum(Days_Elig_post) as Sum_days_post
FROM ``
GROUP BY $Patid,
$Admit_Date,
$Pre_Admit,
$Post_Admit
ERROR: Unrecognized name: Days_Elig_post at [6:5]

Days_Elig_post was defined in the previous block:
SELECT
$Patid,
$Eligeff,
$Eligend,
$Admit_Date,
$Pre_Admit,
$Post_Admit,
DATE_DIFF($Eligend, $Admit_Date, DAY) as Days_Elig_post
FROM ``
Previous block ran fine!

**Comment by vmeau** [comment]
When updating a transform block, I get random errors such as "variable X not recognized" (on simple queries, just pulling variables from a table). I actually need to rerun all blocks prior to the updated block for the error to disappear. I have to click "undo" and then retry on each block. 
I just found out about this testing things out, but this will not be intuitive or practical to users. 
The tool should either do it automatically for them or there should be a message that instructs the user on how to proceed.

**Comment by imathews** [comment]
@vmeau on https://github.com/redivis/meta/issues/35#issuecomment-311424311, I'm pretty sure the issue is the lack of `$` when referencing the previous variable in the sum statement (should be `sum($Days_Elig_post) as Sum_days_post`). Keep me posted if this works, and I'll make a not for better error messages when this is the case.

**Comment by imathews** [comment]
Also, thank you soo much for using github to track these things. As a small note, it'll be super helpful down the line if we can keep issues specific to one bug / feature request, allowing us to check these off down the line. I'm moved https://github.com/redivis/meta/issues/35#issuecomment-311429847 to issue #37

**Comment by vmeau** [comment]
Thanks Ian, you were right! Sorry for the false alarm! 
Will make sure I split issues going forward

**Comment by imathews** [comment]
Great, thank you much. I'm going to close this issue, since other items have been broken out into their own issues. Feel free to open a new issue if you run into further bugs with SQL parsing
